name: Deploy Rails App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Set permissions for SSH directory and key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Install Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Install npm dependencies
        run: |
              npm install
              ls


      # - name: Run npm build
      #   run: npm run build

      - name: Set Python 2 Path
        run: |
          echo "PYTHON=/usr/bin/python2" >> $GITHUB_ENV

      - name: Deploy with Capistrano
        run: |
          pwd
          ls
          bundle exec cap production deploy
