name: Deploy Rails App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0.2'

      - name: Install dependencies
        run: |
          set -e  # Exit on failure
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Upload SSH key (encrypted)
        uses: actions/upload-artifact@v2
        with:
          name: ssh-key
          path: ~/.ssh/id_rsa  # Assuming the key is already added securely to your repository (not tracked in git)

      - name: Download SSH key artifact
        uses: actions/download-artifact@v2
        with:
          name: ssh-key

      - name: Add SSH key with permissions (restricted)
        run: |
          mkdir -p ~/.ssh
          chmod 600 ~/.ssh  # Set strict permissions on the directory
          mv downloaded/ssh-key ~/.ssh/id_rsa  # Downloaded from artifact
          chmod 600 ~/.ssh/id_rsa  # Set strict permissions on the key

      - name: Deploy with Capistrano (using SSH_PRIVATE_KEY env var)
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          set -e  # Exit on failure
          cap production deploy